### ISSUE TITLE
Error in callback:  id_token not present in TokenSet

### ISSUE THREAD

**Issue by perborgen** [UNINETT/dataporten-passportjs-demo#1]
Hey, I'm getting the following error when I'm redirected to the /callback URI.

```
Error processing callback { AssertionError [ERR_ASSERTION]: id_token not present in TokenSet
at Client.validateIdToken (/Users/perharaldborgen/dev/dataporten-passportjs-demo/node_modules/openid-client/lib/client.js:431:7)
at grant.then.then.tokenset (/Users/perharaldborgen/dev/dataporten-passportjs-demo/node_modules/openid-client/lib/client.js:333:32)
at process._tickCallback (internal/process/next_tick.js:68:7)
generatedMessage: false,
name: 'AssertionError [ERR_ASSERTION]',
code: 'ERR_ASSERTION',
actual: undefined,
expected: true,
operator: '==' }
```

Any idea what it could be caused by?

**Comment by olavmrk** [comment]
Just for the record: This issue was solved via email to support@feide.no. It was caused by missing the `openid` scope in the application.
